version: "3.9"

services:
  postgres_db:
    container_name: postgres_db

    image: postgres:14.4-alpine
    env_file:
      - .env

    ports:
      - 5431:5432

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  api_ecommerce:
    container_name: api_eccomerce
    env_file:
      - .env
    build: .
    ports:
      - 3000:3000
    depends_on:
      postgres_db:
        condition: service_healthy
    volumes:
      - .:/app
